apiVersion: v1
kind: ServiceAccount
metadata:
  name: joysafeter-agent-gateway
  namespace: {{ .Release.Namespace }}
{{- with .Values.image.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
