[package]
name = "joysafeter-types"
version = "0.1.0"
edition = "2021"

[dependencies]
joysafeter-entity-id = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
