// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunnerMessage {
    #[prost(oneof = "runner_message::Payload", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub payload: ::core::option::Option<runner_message::Payload>,
}
/// Nested message and enum types in `RunnerMessage`.
pub mod runner_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        Ready(super::RunnerReady),
        #[prost(message, tag = "2")]
        Event(super::RunnerHarnessEvent),
        #[prost(message, tag = "3")]
        Result(super::RunnerHarnessResult),
        #[prost(message, tag = "4")]
        Heartbeat(super::RunnerHeartbeat),
        #[prost(message, tag = "5")]
        Idle(super::RunnerIdle),
        #[prost(message, tag = "6")]
        MemorySync(super::MemoryFileSync),
        #[prost(message, tag = "7")]
        SandboxFileResponse(super::SandboxFileResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunnerReady {
    #[prost(string, tag = "1")]
    pub runner_version: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub available_providers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub sandbox_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_reconnect: bool,
    #[prost(string, optional, tag = "5")]
    pub active_task_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "6")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub runner_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunnerIdle {
    #[prost(string, tag = "1")]
    pub sandbox_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub work_dir: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunnerHarnessEvent {
    #[prost(uint64, tag = "1")]
    pub seq: u64,
    #[prost(int64, tag = "2")]
    pub timestamp_ms: i64,
    #[prost(
        oneof = "runner_harness_event::Event",
        tags = "3, 4, 5, 6, 7, 8, 9, 10, 11, 12"
    )]
    pub event: ::core::option::Option<runner_harness_event::Event>,
}
/// Nested message and enum types in `RunnerHarnessEvent`.
pub mod runner_harness_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "3")]
        Text(super::TextEvent),
        #[prost(message, tag = "4")]
        Thinking(super::ThinkingEvent),
        #[prost(message, tag = "5")]
        ToolUse(super::ToolUseEvent),
        #[prost(message, tag = "6")]
        ToolResult(super::ToolResultEvent),
        #[prost(message, tag = "7")]
        Error(super::ErrorEvent),
        #[prost(message, tag = "8")]
        Status(super::StatusEvent),
        #[prost(message, tag = "9")]
        Log(super::LogEvent),
        #[prost(message, tag = "10")]
        ModelRequestStart(super::ModelRequestStartEvent),
        #[prost(message, tag = "11")]
        ModelRequestEnd(super::ModelRequestEndEvent),
        #[prost(message, tag = "12")]
        TaskNotification(super::TaskNotificationEvent),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextEvent {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThinkingEvent {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolUseEvent {
    #[prost(string, tag = "1")]
    pub tool: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub input_json: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_control_request: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolResultEvent {
    #[prost(string, tag = "1")]
    pub tool: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub output: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorEvent {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusEvent {
    #[prost(string, tag = "1")]
    pub state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEvent {
    #[prost(string, tag = "1")]
    pub level: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelRequestStartEvent {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelRequestEndEvent {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub input_tokens: u64,
    #[prost(uint64, tag = "3")]
    pub output_tokens: u64,
    #[prost(uint64, tag = "4")]
    pub cache_read_tokens: u64,
    #[prost(uint64, tag = "5")]
    pub cache_write_tokens: u64,
}
/// Background sub-agent (Task tool with run_in_background=true) lifecycle.
/// Sourced from claude-code's stream-json `type=system,subtype=task_started|task_progress|task_notification`.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskNotificationEvent {
    /// "started" | "progress" | "completed" | "failed" | "stopped"
    #[prost(string, tag = "1")]
    pub phase: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub tool_use_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Terminal status — only set for completed/failed/stopped events
    #[prost(string, optional, tag = "5")]
    pub status: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub summary: ::core::option::Option<::prost::alloc::string::String>,
    /// Final agent text output, parsed from <result> XML block in task_notification
    #[prost(string, optional, tag = "7")]
    pub result: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub output_file: ::core::option::Option<::prost::alloc::string::String>,
    /// Most recent tool the sub-agent invoked (progress events only)
    #[prost(string, optional, tag = "9")]
    pub last_tool_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag = "10")]
    pub total_tokens: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "11")]
    pub tool_uses: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "12")]
    pub duration_ms: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunnerHarnessResult {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub output: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub usage: ::core::option::Option<TokenUsage>,
    #[prost(int64, tag = "6")]
    pub duration_ms: i64,
    #[prost(string, optional, tag = "7")]
    pub work_dir: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenUsage {
    #[prost(uint64, tag = "1")]
    pub input_tokens: u64,
    #[prost(uint64, tag = "2")]
    pub output_tokens: u64,
    #[prost(uint64, tag = "3")]
    pub cache_read_tokens: u64,
    #[prost(uint64, tag = "4")]
    pub cache_write_tokens: u64,
    #[prost(message, repeated, tag = "5")]
    pub by_model: ::prost::alloc::vec::Vec<ModelUsageEntry>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelUsageEntry {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub input_tokens: u64,
    #[prost(uint64, tag = "3")]
    pub output_tokens: u64,
    #[prost(uint64, tag = "4")]
    pub cache_read_tokens: u64,
    #[prost(uint64, tag = "5")]
    pub cache_write_tokens: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunnerHeartbeat {
    #[prost(int64, tag = "1")]
    pub timestamp_ms: i64,
    /// Runtime activity observed by the runner. The orchestrator uses this as a
    /// runner-side liveness signal for idle reaping: busy heartbeats disarm idle
    /// expiry even when no harness events are flowing yet.
    ///
    /// "busy" | "idle"
    #[prost(string, tag = "2")]
    pub runtime_state: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub active_task_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrchestratorMessage {
    #[prost(oneof = "orchestrator_message::Payload", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub payload: ::core::option::Option<orchestrator_message::Payload>,
}
/// Nested message and enum types in `OrchestratorMessage`.
pub mod orchestrator_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        Start(super::StartTask),
        #[prost(message, tag = "2")]
        Cancel(super::CancelTask),
        #[prost(message, tag = "3")]
        Input(super::SendInput),
        #[prost(message, tag = "4")]
        Shutdown(super::Shutdown),
        #[prost(message, tag = "5")]
        Setup(super::SetupSandbox),
        #[prost(message, tag = "6")]
        MemoryUpdate(super::MemoryFileUpdate),
        #[prost(message, tag = "7")]
        SandboxFileRequest(super::SandboxFileRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxFileRequest {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    /// "list" | "content" | "raw" | "archive"
    #[prost(string, tag = "2")]
    pub operation: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub max_bytes: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxFileEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    /// "file" | "directory"
    #[prost(string, tag = "3")]
    pub file_type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub size: u64,
    #[prost(int64, tag = "5")]
    pub mtime: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SandboxFileResponse {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(string, tag = "3")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub entries: ::prost::alloc::vec::Vec<SandboxFileEntry>,
    /// "utf-8" | "base64"
    #[prost(string, tag = "7")]
    pub encoding: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub content: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "9")]
    pub content_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "10")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(uint64, tag = "12")]
    pub size: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryFileUpdate {
    #[prost(string, tag = "1")]
    pub store_mount_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub relative_path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub operation: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetupSandbox {
    #[prost(message, repeated, tag = "1")]
    pub skills: ::prost::alloc::vec::Vec<SkillArchive>,
    #[prost(message, repeated, tag = "2")]
    pub mcp_servers: ::prost::alloc::vec::Vec<McpConfig>,
    #[prost(message, repeated, tag = "3")]
    pub custom_tools: ::prost::alloc::vec::Vec<CustomTool>,
    #[prost(string, repeated, tag = "4")]
    pub setup_commands: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub work_dir: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "6")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, string", tag = "7")]
    pub secrets: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, optional, tag = "8")]
    pub permission_mode: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "9")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "10")]
    pub model: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "11")]
    pub memory_system_prompt: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "12")]
    pub memory_mounts: ::prost::alloc::vec::Vec<MemoryStoreMount>,
    #[prost(message, repeated, tag = "13")]
    pub files: ::prost::alloc::vec::Vec<FileMount>,
    #[prost(message, repeated, tag = "14")]
    pub file_refs: ::prost::alloc::vec::Vec<FileRef>,
    #[prost(string, repeated, tag = "15")]
    pub allowed_tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "16")]
    pub disallowed_tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "17")]
    pub ask_tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "18")]
    pub repos: ::prost::alloc::vec::Vec<RepoConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryStoreMount {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub mount_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mount_path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub access: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub files: ::prost::alloc::vec::Vec<MemoryFile>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryFile {
    #[prost(string, tag = "1")]
    pub relative_path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemoryFileSync {
    #[prost(string, tag = "1")]
    pub store_mount_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub relative_path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub operation: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartTask {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub prompt: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub system_prompt: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub session_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub model: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "7")]
    pub max_turns: ::core::option::Option<u32>,
    #[prost(uint64, tag = "8")]
    pub timeout_seconds: u64,
    #[prost(map = "string, string", tag = "9")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, string", tag = "10")]
    pub secrets: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, repeated, tag = "11")]
    pub mcp_servers: ::prost::alloc::vec::Vec<McpConfig>,
    #[prost(message, repeated, tag = "12")]
    pub repos: ::prost::alloc::vec::Vec<RepoConfig>,
    #[prost(string, optional, tag = "13")]
    pub work_dir: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "14")]
    pub skills: ::prost::alloc::vec::Vec<SkillArchive>,
    #[prost(string, repeated, tag = "15")]
    pub allowed_tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "16")]
    pub disallowed_tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "17")]
    pub permission_mode: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "18")]
    pub setup_commands: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "19")]
    pub custom_tools: ::prost::alloc::vec::Vec<CustomTool>,
    #[prost(string, repeated, tag = "20")]
    pub ask_tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// "append" (default): --append-system-prompt (CC keeps its built-in prompt)
    /// "replace": --system-prompt (CC built-in prompt is replaced)
    #[prost(string, optional, tag = "21")]
    pub system_prompt_mode: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CustomTool {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub input_schema_json: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkillArchive {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub tar_gz: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub target: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileMount {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileRef {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub size_bytes: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpConfig {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub command: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "4")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "6")]
    pub url: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "7")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(enumeration = "McpTransport", tag = "8")]
    pub transport: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepoConfig {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub branch: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    /// Clone-only credential. Never logged or echoed in API responses.
    #[prost(string, tag = "4")]
    pub authorization_token: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub mount_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelTask {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendInput {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Shutdown {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum McpTransport {
    Unspecified = 0,
    StreamableHttp = 1,
    Sse = 2,
    LocalStdio = 3,
}
impl McpTransport {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MCP_TRANSPORT_UNSPECIFIED",
            Self::StreamableHttp => "MCP_TRANSPORT_STREAMABLE_HTTP",
            Self::Sse => "MCP_TRANSPORT_SSE",
            Self::LocalStdio => "MCP_TRANSPORT_LOCAL_STDIO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MCP_TRANSPORT_UNSPECIFIED" => Some(Self::Unspecified),
            "MCP_TRANSPORT_STREAMABLE_HTTP" => Some(Self::StreamableHttp),
            "MCP_TRANSPORT_SSE" => Some(Self::Sse),
            "MCP_TRANSPORT_LOCAL_STDIO" => Some(Self::LocalStdio),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod agent_bridge_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AgentBridgeServer.
    #[async_trait]
    pub trait AgentBridge: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Session method.
        type SessionStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::OrchestratorMessage, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn session(
            &self,
            request: tonic::Request<tonic::Streaming<super::RunnerMessage>>,
        ) -> std::result::Result<tonic::Response<Self::SessionStream>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct AgentBridgeServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AgentBridgeServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AgentBridgeServer<T>
    where
        T: AgentBridge,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/joysafeter.AgentBridge/Session" => {
                    #[allow(non_camel_case_types)]
                    struct SessionSvc<T: AgentBridge>(pub Arc<T>);
                    impl<
                        T: AgentBridge,
                    > tonic::server::StreamingService<super::RunnerMessage>
                    for SessionSvc<T> {
                        type Response = super::OrchestratorMessage;
                        type ResponseStream = T::SessionStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::RunnerMessage>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AgentBridge>::session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SessionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AgentBridgeServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "joysafeter.AgentBridge";
    impl<T> tonic::server::NamedService for AgentBridgeServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
