"""
ArtifactCollector: collect agent run outputs into a unified artifacts directory.

When using FilesystemBackend with root_dir pointing to the run directory,
no copy is needed; this module writes _manifest.json after the run.
"""

from __future__ import annotations

import json
import mimetypes
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from loguru import logger

from app.utils.path_utils import sanitize_path_component

MANIFEST_FILENAME = "_manifest.json"


def _default_artifacts_root() -> Path:
    return Path.home() / ".agent-platform" / "agent-artifacts"


def resolve_artifacts_root() -> Path:
    env = os.getenv("AGENT_ARTIFACTS_ROOT", "").strip()
    if env:
        return Path(env).expanduser().resolve()
    return _default_artifacts_root().resolve()


class ArtifactCollector:
    """Collects and indexes agent run artifacts under a unified directory layout."""

    def __init__(self, artifacts_root: str | Path | None = None) -> None:
        self.root = Path(artifacts_root) if artifacts_root else resolve_artifacts_root()
        self.root = self.root.resolve()

    def get_run_dir(
        self,
        user_id: str,
        thread_id: str,
        run_id: str,
    ) -> Path:
        """Return the run artifacts directory path (sanitized, no fs ops)."""
        uid = sanitize_path_component(user_id, default="default")
        tid = sanitize_path_component(thread_id, default="default")
        rid = sanitize_path_component(run_id, default="default")
        return self.root / uid / tid / rid

    def ensure_run_dir(
        self,
        user_id: str,
        thread_id: str,
        run_id: str,
    ) -> Path:
        """Create the run directory if it does not exist; return its path."""
        run_dir = self.get_run_dir(user_id, thread_id, run_id)
        run_dir.mkdir(parents=True, exist_ok=True)
        return run_dir

    def _collect_file_entries(self, run_dir: Path) -> list[dict[str, Any]]:
        """Scan run_dir for files (excluding _manifest.json) and return manifest file entries."""
        entries: list[dict[str, Any]] = []
        run_dir_resolved = run_dir.resolve()
        for path in run_dir.rglob("*"):
            if not path.is_file():
                continue
            try:
                rel = path.resolve().relative_to(run_dir_resolved)
                rel_str = rel.as_posix()
                if rel_str == MANIFEST_FILENAME:
                    continue
                size = path.stat().st_size
                guess_type, _ = mimetypes.guess_type(str(path))
                entries.append(
                    {
                        "path": rel_str,
                        "size": size,
                        "type": guess_type or "application/octet-stream",
                    }
                )
            except (ValueError, OSError) as e:
                logger.warning(f"[ArtifactCollector] Skip file {path}: {e}")
        return entries

    def write_manifest(
        self,
        run_dir: Path,
        metadata: dict[str, Any],
    ) -> None:
        """
        Scan run_dir for files, then write _manifest.json with metadata and file list.

        metadata may include: run_id, thread_id, user_id, agent_type, graph_id,
        started_at, completed_at, status. Files list is generated by scanning.
        """
        run_dir = Path(run_dir).resolve()
        if not run_dir.exists() or not run_dir.is_dir():
            logger.warning(f"[ArtifactCollector] Run dir does not exist or is not a directory: {run_dir}")
            return

        # Ensure run_dir is under self.root (security)
        try:
            run_dir.relative_to(self.root)
        except ValueError:
            logger.error(f"[ArtifactCollector] run_dir {run_dir} is not under artifacts root {self.root}")
            return

        payload = dict(metadata)
        payload.setdefault("completed_at", datetime.now(timezone.utc).isoformat())
        payload["files"] = self._collect_file_entries(run_dir)

        manifest_path = run_dir / MANIFEST_FILENAME
        with manifest_path.open("w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2, default=str)
        logger.debug(f"[ArtifactCollector] Wrote manifest at {manifest_path}")
