apiVersion: v1
kind: Service
metadata:
  name: joysafeter-orchestrator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: joysafeter-orchestrator
  ports:
  - port: {{ .Values.orchestrator.grpc.port }}
    targetPort: grpc
    name: grpc
  - port: 9091
    targetPort: health
    name: health
