"""Cross-language cipher vectors for the `enc:v1:` credential envelope.

These vectors are the shared contract between the Python `CredentialCipher`
and the Rust `VaultCipher`: the fixture is generated by the Python cipher with
a fixed key, and both languages must decrypt every entry to the same plaintext.
"""

import json
from pathlib import Path

import pytest

from app.joysafeter_shared.security.credential_cipher import (
    CredentialCipher,
    CredentialCiphertextError,
)

pytestmark = pytest.mark.no_db

_VECTORS_PATH = Path(__file__).parent / "fixtures" / "cipher_vectors.json"


def _load_vectors() -> dict:
    return json.loads(_VECTORS_PATH.read_text(encoding="utf-8"))


def _cipher() -> CredentialCipher:
    return CredentialCipher(_load_vectors()["key"])


def test_fixture_uses_v1_envelope():
    vectors = _load_vectors()
    assert vectors["envelope"] == "enc:v1:"
    assert vectors["vectors"], "expected at least one cross-language vector"
    for entry in vectors["vectors"]:
        assert entry["ciphertext"].startswith("enc:v1:")


def test_encrypt_emits_v1_prefix():
    cipher = _cipher()
    stored = cipher.encrypt("secret-value")
    assert stored.startswith("enc:v1:")
    assert stored != "secret-value"


def test_decrypt_stored_matches_every_vector():
    cipher = _cipher()
    for entry in _load_vectors()["vectors"]:
        assert cipher.decrypt_stored(entry["ciphertext"]) == entry["plaintext"]


def test_round_trip_through_v1_envelope():
    cipher = _cipher()
    for entry in _load_vectors()["vectors"]:
        stored = cipher.encrypt(entry["plaintext"])
        assert stored.startswith("enc:v1:")
        assert cipher.decrypt_stored(stored) == entry["plaintext"]


def test_bare_enc_prefix_without_version_is_read_as_v1():
    cipher = _cipher()
    entry = next(item for item in _load_vectors()["vectors"] if item["plaintext"])
    bare = "enc:" + entry["ciphertext"][len("enc:v1:") :]

    assert cipher.decrypt_stored(bare) == entry["plaintext"]


def test_empty_string_is_the_absent_credential_sentinel():
    assert _cipher().decrypt_stored("") == ""


def test_unknown_versioned_envelope_is_rejected():
    with pytest.raises(CredentialCiphertextError, match="Unsupported credential envelope"):
        _cipher().decrypt_stored("enc:v2:not-supported")


def test_corrupt_legacy_envelope_is_rejected():
    with pytest.raises(CredentialCiphertextError, match="Failed to decrypt"):
        _cipher().decrypt_stored("enc:not-valid-base64")


def test_normalize_stored_is_idempotent_for_all_supported_generations():
    cipher = _cipher()
    entry = next(item for item in _load_vectors()["vectors"] if item["plaintext"])
    current = entry["ciphertext"]
    legacy = "enc:" + current[len("enc:v1:") :]

    assert cipher.normalize_stored("") == ""
    assert cipher.normalize_stored(current) == current
    assert cipher.normalize_stored(legacy) == current

    normalized_plaintext = cipher.normalize_stored(entry["plaintext"])
    assert normalized_plaintext.startswith("enc:v1:")
    assert cipher.decrypt_stored(normalized_plaintext) == entry["plaintext"]
    assert cipher.normalize_stored(normalized_plaintext) == normalized_plaintext
