"""Cross-language cipher vectors for the `enc:v1:` credential envelope.

These vectors are the shared contract between the Python `CredentialCipher`
and the Rust `VaultCipher`: the fixture is generated by the Python cipher with
a fixed key, and both languages must decrypt every entry to the same plaintext.
"""

import json
from pathlib import Path

import pytest

from app.joysafeter_shared.security.credential_cipher import (
    CredentialCipher,
    CredentialCiphertextError,
)

pytestmark = pytest.mark.no_db

_VECTORS_PATH = Path(__file__).parent / "fixtures" / "cipher_vectors.json"


def _load_vectors() -> dict:
    return json.loads(_VECTORS_PATH.read_text(encoding="utf-8"))


def _cipher() -> CredentialCipher:
    return CredentialCipher(_load_vectors()["key"])


def test_fixture_uses_v1_envelope():
    vectors = _load_vectors()
    assert vectors["envelope"] == "enc:v1:"
    assert vectors["vectors"], "expected at least one cross-language vector"
    for entry in vectors["vectors"]:
        assert entry["ciphertext"].startswith("enc:v1:")


def test_encrypt_emits_v1_prefix():
    cipher = _cipher()
    stored = cipher.encrypt("secret-value")
    assert stored.startswith("enc:v1:")
    assert stored != "secret-value"


def test_decrypt_stored_matches_every_vector():
    cipher = _cipher()
    for entry in _load_vectors()["vectors"]:
        assert cipher.decrypt_stored(entry["ciphertext"]) == entry["plaintext"]


def test_round_trip_through_v1_envelope():
    cipher = _cipher()
    for entry in _load_vectors()["vectors"]:
        stored = cipher.encrypt(entry["plaintext"])
        assert stored.startswith("enc:v1:")
        assert cipher.decrypt_stored(stored) == entry["plaintext"]


def test_bare_enc_prefix_without_version_is_rejected():
    """A bare `enc:` payload (no `v1:` version) must be refused: v1 is the only
    accepted envelope and there is no legacy read path."""
    cipher = _cipher()
    entry = _load_vectors()["vectors"][0]
    bare = "enc:" + entry["ciphertext"][len("enc:v1:") :]
    with pytest.raises(CredentialCiphertextError):
        cipher.decrypt_stored(bare)
