"""Cross-language cipher vectors and versioned credential-envelope behavior.

These vectors are the shared contract between the Python `CredentialCipher`
and the Rust `VaultCipher`: the fixture is generated by the Python cipher with
a fixed key, and both languages must decrypt every entry to the same plaintext.
"""

import json
from pathlib import Path

import pytest

from app.joysafeter_shared.security.credential_cipher import (
    CredentialCipher,
    CredentialCipherConfigurationError,
    CredentialCiphertextError,
)

pytestmark = pytest.mark.no_db

_VECTORS_PATH = Path(__file__).parent / "fixtures" / "cipher_vectors.json"


def _load_vectors() -> dict:
    return json.loads(_VECTORS_PATH.read_text(encoding="utf-8"))


def _cipher() -> CredentialCipher:
    return CredentialCipher(_load_vectors()["key"])


def _keyring() -> str:
    return json.dumps(
        {
            "active-2026-08": CredentialCipher.generate_key(),
            "previous-2026-07": CredentialCipher.generate_key(),
        }
    )


def test_fixture_uses_v1_envelope():
    vectors = _load_vectors()
    assert vectors["envelope"] == "enc:v1:"
    assert vectors["vectors"], "expected at least one cross-language vector"
    for entry in vectors["vectors"]:
        assert entry["ciphertext"].startswith("enc:v1:")


def test_encrypt_emits_v1_prefix():
    cipher = _cipher()
    stored = cipher.encrypt("secret-value")
    assert stored.startswith("enc:v1:")
    assert stored != "secret-value"


def test_keyring_encrypt_emits_v2_prefix_with_write_key_id():
    cipher = CredentialCipher(
        keyring_json=_keyring(),
        write_key_id="active-2026-08",
    )

    stored = cipher.encrypt("secret-value")

    assert stored.startswith("enc:v2:active-2026-08:")
    assert cipher.decrypt_stored(stored) == "secret-value"


def test_v2_envelope_is_decrypted_by_embedded_key_id():
    keyring = _keyring()
    old_writer = CredentialCipher(
        keyring_json=keyring,
        write_key_id="previous-2026-07",
    )
    current_reader = CredentialCipher(
        keyring_json=keyring,
        write_key_id="active-2026-08",
    )

    stored = old_writer.encrypt("rotated-secret")

    assert stored.startswith("enc:v2:previous-2026-07:")
    assert current_reader.decrypt_stored(stored) == "rotated-secret"


def test_v2_envelope_authenticates_embedded_key_id():
    shared_key = CredentialCipher.generate_key()
    cipher = CredentialCipher(
        keyring_json=json.dumps(
            {
                "active-2026-08": shared_key,
                "alias-2026-08": shared_key,
            }
        ),
        write_key_id="active-2026-08",
    )
    stored = cipher.encrypt("secret-value")
    relabeled = stored.replace(
        "enc:v2:active-2026-08:",
        "enc:v2:alias-2026-08:",
        1,
    )

    with pytest.raises(CredentialCiphertextError, match="Failed to decrypt"):
        cipher.decrypt_stored(relabeled)


def test_pre_release_v2_envelope_without_authenticated_prefix_is_rejected():
    cipher = CredentialCipher(
        keyring_json=json.dumps({"active-2026-08": "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="}),
        write_key_id="active-2026-08",
    )

    with pytest.raises(CredentialCiphertextError, match="Failed to decrypt"):
        cipher.decrypt_stored("enc:v2:active-2026-08:XPCBUDirm4X13pqPmVYdF8XL0Lo+i131xweAbmv4iU7fD8/fXnmD")


def test_keyring_mode_continues_reading_v1_through_legacy_key():
    legacy_key = _load_vectors()["key"]
    legacy_stored = CredentialCipher(legacy_key).encrypt("legacy-secret")
    cipher = CredentialCipher(
        legacy_key,
        keyring_json=_keyring(),
        write_key_id="active-2026-08",
    )

    assert cipher.decrypt_stored(legacy_stored) == "legacy-secret"


def test_decrypt_stored_matches_every_vector():
    cipher = _cipher()
    for entry in _load_vectors()["vectors"]:
        assert cipher.decrypt_stored(entry["ciphertext"]) == entry["plaintext"]


def test_round_trip_through_v1_envelope():
    cipher = _cipher()
    for entry in _load_vectors()["vectors"]:
        stored = cipher.encrypt(entry["plaintext"])
        assert stored.startswith("enc:v1:")
        assert cipher.decrypt_stored(stored) == entry["plaintext"]


def test_bare_enc_prefix_without_version_is_read_as_v1():
    cipher = _cipher()
    entry = next(item for item in _load_vectors()["vectors"] if item["plaintext"])
    bare = "enc:" + entry["ciphertext"][len("enc:v1:") :]

    assert cipher.decrypt_stored(bare) == entry["plaintext"]


def test_empty_string_is_the_absent_credential_sentinel():
    assert _cipher().decrypt_stored("") == ""


def test_unknown_versioned_envelope_is_rejected():
    with pytest.raises(CredentialCiphertextError, match="Unsupported credential envelope"):
        _cipher().decrypt_stored("enc:v2:not-supported")


def test_unknown_v2_key_id_is_rejected():
    keyring = _keyring()
    cipher = CredentialCipher(
        keyring_json=keyring,
        write_key_id="active-2026-08",
    )
    stored = cipher.encrypt("secret")
    unknown_key_stored = stored.replace(
        "enc:v2:active-2026-08:",
        "enc:v2:retired-2025-01:",
        1,
    )

    with pytest.raises(CredentialCipherConfigurationError, match="key id is not configured"):
        cipher.decrypt_stored(unknown_key_stored)


def test_corrupt_legacy_envelope_is_rejected():
    with pytest.raises(CredentialCiphertextError, match="Failed to decrypt"):
        _cipher().decrypt_stored("enc:not-valid-base64")


def test_normalize_stored_is_idempotent_for_all_supported_generations():
    cipher = _cipher()
    entry = next(item for item in _load_vectors()["vectors"] if item["plaintext"])
    current = entry["ciphertext"]
    legacy = "enc:" + current[len("enc:v1:") :]

    assert cipher.normalize_stored("") == ""
    assert cipher.normalize_stored(current) == current
    assert cipher.normalize_stored(legacy) == current

    normalized_plaintext = cipher.normalize_stored(entry["plaintext"])
    assert normalized_plaintext.startswith("enc:v1:")
    assert cipher.decrypt_stored(normalized_plaintext) == entry["plaintext"]
    assert cipher.normalize_stored(normalized_plaintext) == normalized_plaintext


def test_normalize_stored_rewraps_old_v2_and_v1_with_active_key():
    legacy_key = _load_vectors()["key"]
    keyring = _keyring()
    old_writer = CredentialCipher(
        keyring_json=keyring,
        write_key_id="previous-2026-07",
    )
    current = CredentialCipher(
        legacy_key,
        keyring_json=keyring,
        write_key_id="active-2026-08",
    )
    old_v2 = old_writer.encrypt("old-v2")
    old_v1 = CredentialCipher(legacy_key).encrypt("old-v1")

    normalized_v2 = current.normalize_stored(old_v2)
    normalized_v1 = current.normalize_stored(old_v1)

    assert normalized_v2.startswith("enc:v2:active-2026-08:")
    assert normalized_v1.startswith("enc:v2:active-2026-08:")
    assert current.decrypt_stored(normalized_v2) == "old-v2"
    assert current.decrypt_stored(normalized_v1) == "old-v1"
