"""init JoySafeter schema (squashed)

Single squashed initial migration for fresh deployments. Replaces the prior
14-migration chain (initial v1 schema + skill feature additions + four
``drop_v1_dead_tables`` passes + data backfills) with one explicit-DDL step
that builds the final 33-table managed-agent schema.

Generated via ``alembic revision --autogenerate`` against an empty database so
every table, column, server_default, conditional index and constraint matches
the current ORM models. Historical data-backfill steps are intentionally
dropped (a fresh database has no rows to migrate).

Revision ID: 20260627_000001
Revises:
Create Date: 2026-06-27 00:00:00.000000+00:00
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260627_000001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "joysafeter_organizations",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("logo", sa.String(length=500), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("org_usage_limit", sa.Numeric(), nullable=True),
        sa.Column("storage_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("departed_member_usage", sa.Numeric(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_organizations")),
    )
    op.create_table(
        "joysafeter_security_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("user_email", sa.String(length=255), nullable=True),
        sa.Column(
            "event_type",
            sa.String(length=50),
            nullable=False,
            comment="event type: login, logout, password_change, password_reset, 2fa_enable, account_lock, etc.",
        ),
        sa.Column(
            "event_status", sa.String(length=20), nullable=False, comment="event status: success, failure, blocked"
        ),
        sa.Column("ip_address", sa.String(length=255), nullable=False),
        sa.Column("user_agent", sa.String(length=1024), nullable=True),
        sa.Column("device_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=10), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="extra info such as error reason, target entity, etc.",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_security_audit_logs")),
    )
    op.create_index(
        "ix_joysafeter_security_audit_logs_created_at", "joysafeter_security_audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_joysafeter_security_audit_logs_event_status",
        "joysafeter_security_audit_logs",
        ["event_status"],
        unique=False,
    )
    op.create_index(
        "ix_joysafeter_security_audit_logs_event_type", "joysafeter_security_audit_logs", ["event_type"], unique=False
    )
    op.create_index(
        "ix_joysafeter_security_audit_logs_user_event",
        "joysafeter_security_audit_logs",
        ["user_id", "event_type"],
        unique=False,
    )
    op.create_index(
        "ix_joysafeter_security_audit_logs_user_id", "joysafeter_security_audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "joysafeter_users",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("password_reset_token", sa.String(length=255), nullable=True),
        sa.Column("password_reset_expires", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_verify_token", sa.String(length=255), nullable=True),
        sa.Column("email_verify_expires", sa.DateTime(timezone=True), nullable=True),
        sa.Column("image", sa.String(length=1024), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("is_super_user", sa.Boolean(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_reason", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_users")),
    )
    op.create_index(op.f("ix_joysafeter_users_email"), "joysafeter_users", ["email"], unique=True)
    op.create_table(
        "joysafeter_auth_sessions",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("ip_address", sa.String(length=255), nullable=True),
        sa.Column("user_agent", sa.String(length=1024), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("active_organization_id", sa.String(length=255), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("is_trusted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_organization_id"],
            ["joysafeter_organizations.id"],
            name=op.f("fk_joysafeter_auth_sessions_active_organization_id_joysafeter_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_auth_sessions_user_id_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_auth_sessions")),
        sa.UniqueConstraint("token", name=op.f("uq_joysafeter_auth_sessions_token")),
    )
    op.create_index("ix_joysafeter_auth_sessions_token", "joysafeter_auth_sessions", ["token"], unique=True)
    op.create_index("ix_joysafeter_auth_sessions_user_id", "joysafeter_auth_sessions", ["user_id"], unique=False)
    op.create_table(
        "joysafeter_oauth_account",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_account_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_userinfo", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_oauth_account_user_id_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_oauth_account")),
    )
    op.create_index(
        "ix_joysafeter_oauth_account_provider_account",
        "joysafeter_oauth_account",
        ["provider", "provider_account_id"],
        unique=True,
    )
    op.create_index("ix_joysafeter_oauth_account_user_id", "joysafeter_oauth_account", ["user_id"], unique=False)
    op.create_table(
        "joysafeter_organization_members",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("organization_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["joysafeter_organizations.id"],
            name=op.f("fk_joysafeter_organization_members_organization_id_joysafeter_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_organization_members_user_id_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_organization_members")),
    )
    op.create_index(
        "ix_joysafeter_organization_members_organization_id",
        "joysafeter_organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_joysafeter_organization_members_user_id", "joysafeter_organization_members", ["user_id"], unique=False
    )
    op.create_table(
        "joysafeter_organization_projects",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["joysafeter_organizations.id"],
            name=op.f("fk_joysafeter_organization_projects_org_id_joysafeter_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_organization_projects")),
        sa.UniqueConstraint("org_id", "slug", name="uq_joysafeter_organization_projects_org_slug"),
    )
    op.create_index(
        "ix_joysafeter_organization_projects_org_id", "joysafeter_organization_projects", ["org_id"], unique=False
    )
    op.create_table(
        "joysafeter_agents",
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("engine_kind", sa.Text(), nullable=False),
        sa.Column("model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("env", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("mcp_configs", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("tools", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("agents", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("commands", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("permission_mode", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("multiagent", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("environment_ref", sa.Text(), nullable=True),
        sa.Column("secret_ref", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_agents_project_id_joysafeter_organization_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_agents")),
        sa.UniqueConstraint("name", name="idx_ca_name_unique"),
    )
    op.create_index("idx_ca_created_at", "joysafeter_agents", ["created_at"], unique=False)
    op.create_index("idx_ca_project", "joysafeter_agents", ["project_id"], unique=False)
    op.create_index(op.f("ix_joysafeter_agents_project_id"), "joysafeter_agents", ["project_id"], unique=False)
    op.create_table(
        "joysafeter_api_keys",
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("org_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("key_prefix", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_api_keys_created_by_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["joysafeter_organizations.id"],
            name=op.f("fk_joysafeter_api_keys_org_id_joysafeter_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_api_keys_project_id_joysafeter_organization_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_api_keys")),
    )
    op.create_index("idx_cak_key_hash", "joysafeter_api_keys", ["key_hash"], unique=False)
    op.create_index("idx_cak_org", "joysafeter_api_keys", ["org_id"], unique=False)
    op.create_index("idx_cak_project", "joysafeter_api_keys", ["project_id"], unique=False)
    op.create_table(
        "joysafeter_environments",
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("image_tag", sa.Text(), nullable=True),
        sa.Column("image_version", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_environments_project_id_joysafeter_organization_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_environments")),
        sa.UniqueConstraint("name", name=op.f("uq_joysafeter_environments_name")),
    )
    op.create_index(
        op.f("ix_joysafeter_environments_project_id"), "joysafeter_environments", ["project_id"], unique=False
    )
    op.create_table(
        "joysafeter_memory_stores",
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_memory_stores_project_id_joysafeter_organization_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_memory_stores")),
    )
    op.create_index(
        op.f("ix_joysafeter_memory_stores_project_id"), "joysafeter_memory_stores", ["project_id"], unique=False
    )
    op.create_table(
        "joysafeter_project_members",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_project_members_project_id_joysafeter_organization_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_project_members_user_id_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_project_members")),
        sa.UniqueConstraint("project_id", "user_id", name="uq_joysafeter_project_members_project_user"),
    )
    op.create_index(
        "ix_joysafeter_project_members_project_id", "joysafeter_project_members", ["project_id"], unique=False
    )
    op.create_index("ix_joysafeter_project_members_user_id", "joysafeter_project_members", ["user_id"], unique=False)
    op.create_table(
        "joysafeter_sandboxes",
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("chat_session_id", sa.UUID(), nullable=True),
        sa.Column("image", sa.Text(), nullable=False),
        sa.Column("last_task_id", sa.UUID(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("idle_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("destroyed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_path", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_sandboxes_project_id_joysafeter_organization_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_sandboxes")),
    )
    op.create_index(
        "idx_csb_active_session_unique",
        "joysafeter_sandboxes",
        ["chat_session_id"],
        unique=True,
        postgresql_where="chat_session_id IS NOT NULL AND destroyed_at IS NULL AND status IN ('creating', 'provisioning', 'idle', 'running', 'stopped', 'error')",
    )
    op.create_index(
        "idx_csb_pool", "joysafeter_sandboxes", ["created_at"], unique=False, postgresql_where="status = 'pooled'"
    )
    op.create_index("idx_csb_project", "joysafeter_sandboxes", ["project_id"], unique=False)
    op.create_index(
        "idx_csb_session",
        "joysafeter_sandboxes",
        ["chat_session_id"],
        unique=False,
        postgresql_where="chat_session_id IS NOT NULL",
    )
    op.create_index("idx_csb_status", "joysafeter_sandboxes", ["status"], unique=False)
    op.create_index(op.f("ix_joysafeter_sandboxes_project_id"), "joysafeter_sandboxes", ["project_id"], unique=False)
    op.create_table(
        "joysafeter_secrets",
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=64), server_default="custom", nullable=False),
        sa.Column("protocol", sa.String(length=64), server_default="custom", nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_secrets_project_id_joysafeter_organization_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_secrets")),
        sa.UniqueConstraint("name", name="idx_cs_name_unique"),
    )
    op.create_index(op.f("ix_joysafeter_secrets_project_id"), "joysafeter_secrets", ["project_id"], unique=False)
    op.create_table(
        "joysafeter_skills",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("root_path", sa.String(length=512), nullable=True),
        sa.Column("owner_id", sa.String(length=255), nullable=True),
        sa.Column("created_by_id", sa.String(length=255), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("license", sa.String(length=100), nullable=True),
        sa.Column("compatibility", sa.String(length=500), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("security_status", sa.String(length=32), nullable=False),
        sa.Column("security_score", sa.Integer(), nullable=True),
        sa.Column("security_severity", sa.String(length=32), nullable=True),
        sa.Column("security_recommendation", sa.String(length=32), nullable=True),
        sa.Column("security_scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("security_scan_id", sa.UUID(), nullable=True),
        sa.Column("security_scan_hash", sa.String(length=64), nullable=True),
        sa.Column("security_issues_count", sa.Integer(), nullable=False),
        sa.Column("security_critical_count", sa.Integer(), nullable=False),
        sa.Column("security_high_count", sa.Integer(), nullable=False),
        sa.Column("security_medium_count", sa.Integer(), nullable=False),
        sa.Column("security_low_count", sa.Integer(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_skills_created_by_id_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_skills_owner_id_joysafeter_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_skills_project_id_joysafeter_organization_projects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_skills")),
        sa.UniqueConstraint("owner_id", "name", name="skills_owner_name_unique"),
    )
    op.create_index("skills_created_by_idx", "joysafeter_skills", ["created_by_id"], unique=False)
    op.create_index("skills_lifecycle_status_idx", "joysafeter_skills", ["lifecycle_status"], unique=False)
    op.create_index("skills_owner_idx", "joysafeter_skills", ["owner_id"], unique=False)
    op.create_index("skills_project_idx", "joysafeter_skills", ["project_id"], unique=False)
    op.create_index("skills_public_idx", "joysafeter_skills", ["is_public"], unique=False)
    op.create_index(
        "skills_security_recommendation_idx", "joysafeter_skills", ["security_recommendation"], unique=False
    )
    op.create_index("skills_security_severity_idx", "joysafeter_skills", ["security_severity"], unique=False)
    op.create_index("skills_security_status_idx", "joysafeter_skills", ["security_status"], unique=False)
    op.create_index("skills_tags_idx", "joysafeter_skills", ["tags"], unique=False, postgresql_using="gin")
    op.create_index("skills_visibility_idx", "joysafeter_skills", ["visibility"], unique=False)
    op.create_table(
        "joysafeter_vaults",
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_vaults_project_id_joysafeter_organization_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_vaults")),
        sa.UniqueConstraint("name", name="idx_cv_name"),
    )
    op.create_index("idx_cv_project", "joysafeter_vaults", ["project_id"], unique=False)
    op.create_index(op.f("ix_joysafeter_vaults_project_id"), "joysafeter_vaults", ["project_id"], unique=False)
    op.create_table(
        "joysafeter_agent_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["joysafeter_agents.id"], name=op.f("fk_joysafeter_agent_versions_agent_id_joysafeter_agents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_agent_versions")),
        sa.UniqueConstraint("agent_id", "version", name=op.f("uq_joysafeter_agent_versions_agent_id")),
    )
    op.create_table(
        "joysafeter_memories",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["joysafeter_memory_stores.id"],
            name=op.f("fk_joysafeter_memories_store_id_joysafeter_memory_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_memories")),
        sa.UniqueConstraint("store_id", "path", name=op.f("uq_joysafeter_memories_store_id")),
    )
    op.create_table(
        "joysafeter_memory_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_sha256", sa.Text(), nullable=True),
        sa.Column("content_size_bytes", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("api_key_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("redacted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redacted_by", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["joysafeter_memory_stores.id"],
            name=op.f("fk_joysafeter_memory_versions_store_id_joysafeter_memory_stores"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_memory_versions")),
    )
    op.create_table(
        "joysafeter_sessions",
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("stop_reason", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "usage",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"input_tokens":0,"output_tokens":0,"cache_creation_input_tokens":0,"cache_read_input_tokens":0}',
            nullable=False,
        ),
        sa.Column("active_seconds", sa.Float(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("vault_ids", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("agent_version", sa.Integer(), nullable=True),
        sa.Column("agent_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("environment_ref", sa.Text(), nullable=True),
        sa.Column("last_harness_session_id", sa.Text(), nullable=True),
        sa.Column("last_work_dir", sa.Text(), nullable=True),
        sa.Column("last_sandbox_id", sa.UUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["joysafeter_agents.id"], name=op.f("fk_joysafeter_sessions_agent_id_joysafeter_agents")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_sessions_project_id_joysafeter_organization_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_sessions")),
    )
    op.create_index("idx_csess_agent", "joysafeter_sessions", ["agent_id"], unique=False)
    op.create_index("idx_csess_created", "joysafeter_sessions", ["created_at"], unique=False)
    op.create_index("idx_csess_project", "joysafeter_sessions", ["project_id"], unique=False)
    op.create_index(op.f("ix_joysafeter_sessions_project_id"), "joysafeter_sessions", ["project_id"], unique=False)
    op.create_table(
        "joysafeter_skill_collaborators",
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("viewer", "editor", "publisher", "admin", name="collaborator_role", create_constraint=True),
            nullable=False,
        ),
        sa.Column("invited_by", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_skill_collaborators_invited_by_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["joysafeter_skills.id"],
            name=op.f("fk_joysafeter_skill_collaborators_skill_id_joysafeter_skills"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_skill_collaborators_user_id_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_skill_collaborators")),
        sa.UniqueConstraint("skill_id", "user_id", name="skill_collaborators_skill_user_unique"),
    )
    op.create_index(
        "skill_collaborators_user_skill_idx", "joysafeter_skill_collaborators", ["user_id", "skill_id"], unique=False
    )
    op.create_table(
        "joysafeter_skill_files",
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("storage_type", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["joysafeter_skills.id"],
            name=op.f("fk_joysafeter_skill_files_skill_id_joysafeter_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_skill_files")),
    )
    op.create_index("skill_files_path_idx", "joysafeter_skill_files", ["skill_id", "path"], unique=False)
    op.create_index("skill_files_skill_idx", "joysafeter_skill_files", ["skill_id"], unique=False)
    op.create_table(
        "joysafeter_skill_security_scans",
        sa.Column("skill_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("owner_id", sa.String(length=255), nullable=True),
        sa.Column("created_by_id", sa.String(length=255), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("target_name", sa.String(length=128), nullable=True),
        sa.Column("target_hash", sa.String(length=64), nullable=False),
        sa.Column("scanner", sa.String(length=64), nullable=False),
        sa.Column("scanner_version", sa.String(length=64), nullable=True),
        sa.Column("ruleset_version", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("severity", sa.String(length=32), nullable=True),
        sa.Column("recommendation", sa.String(length=32), nullable=True),
        sa.Column("issues_count", sa.Integer(), nullable=False),
        sa.Column("critical_count", sa.Integer(), nullable=False),
        sa.Column("high_count", sa.Integer(), nullable=False),
        sa.Column("medium_count", sa.Integer(), nullable=False),
        sa.Column("low_count", sa.Integer(), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_skill_security_scans_created_by_id_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_skill_security_scans_owner_id_joysafeter_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_skill_security_scans_project_id_joysafeter_organization_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["joysafeter_skills.id"],
            name=op.f("fk_joysafeter_skill_security_scans_skill_id_joysafeter_skills"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_skill_security_scans")),
    )
    op.create_index(
        "skill_security_scans_owner_created_idx",
        "joysafeter_skill_security_scans",
        ["owner_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "skill_security_scans_project_created_idx",
        "joysafeter_skill_security_scans",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "skill_security_scans_recommendation_created_idx",
        "joysafeter_skill_security_scans",
        ["recommendation", "created_at"],
        unique=False,
    )
    op.create_index(
        "skill_security_scans_severity_created_idx",
        "joysafeter_skill_security_scans",
        ["severity", "created_at"],
        unique=False,
    )
    op.create_index(
        "skill_security_scans_skill_created_idx",
        "joysafeter_skill_security_scans",
        ["skill_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "skill_security_scans_status_created_idx",
        "joysafeter_skill_security_scans",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "skill_security_scans_target_hash_idx", "joysafeter_skill_security_scans", ["target_hash"], unique=False
    )
    op.create_table(
        "joysafeter_skill_usage_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=True),
        sa.Column("skill_version", sa.String(length=64), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.String(length=255), nullable=True),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["joysafeter_skills.id"],
            name=op.f("fk_joysafeter_skill_usage_log_skill_id_joysafeter_skills"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_skill_usage_log")),
    )
    op.create_index(
        "skill_usage_log_project_created_idx", "joysafeter_skill_usage_log", ["project_id", "created_at"], unique=False
    )
    op.create_index(
        "skill_usage_log_session_created_idx", "joysafeter_skill_usage_log", ["session_id", "created_at"], unique=False
    )
    op.create_index(
        "skill_usage_log_skill_created_idx", "joysafeter_skill_usage_log", ["skill_id", "created_at"], unique=False
    )
    op.create_table(
        "joysafeter_vault_credentials",
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("credential_type", sa.Text(), nullable=False),
        sa.Column("mcp_server_url", sa.Text(), nullable=False),
        sa.Column("token_value", sa.Text(), nullable=False),
        sa.Column("oauth_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["vault_id"],
            ["joysafeter_vaults.id"],
            name=op.f("fk_joysafeter_vault_credentials_vault_id_joysafeter_vaults"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_vault_credentials")),
        sa.UniqueConstraint("vault_id", "mcp_server_url", name="idx_cvc_url"),
    )
    op.create_table(
        "joysafeter_files",
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("purpose", sa.String(length=50), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("downloadable", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_files_project_id_joysafeter_organization_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["joysafeter_sessions.id"],
            name=op.f("fk_joysafeter_files_session_id_joysafeter_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_files")),
    )
    op.create_index(
        "idx_joysafeter_files_project_created", "joysafeter_files", ["project_id", "created_at"], unique=False
    )
    op.create_index("idx_joysafeter_files_session", "joysafeter_files", ["session_id"], unique=False)
    op.create_index(op.f("ix_joysafeter_files_project_id"), "joysafeter_files", ["project_id"], unique=False)
    op.create_table(
        "joysafeter_session_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["joysafeter_sessions.id"],
            name=op.f("fk_joysafeter_session_events_session_id_joysafeter_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_session_events")),
        sa.UniqueConstraint("session_id", "seq", name=op.f("uq_joysafeter_session_events_session_id")),
    )
    op.create_index("idx_cse_created_at", "joysafeter_session_events", ["created_at"], unique=False)
    op.create_index("idx_cse_event_created", "joysafeter_session_events", ["event_type", "created_at"], unique=False)
    op.create_index(
        "idx_cse_session_event_seq", "joysafeter_session_events", ["session_id", "event_type", "seq"], unique=False
    )
    op.create_index(
        "idx_cse_session_processed_event",
        "joysafeter_session_events",
        ["session_id", "processed_at", "event_type"],
        unique=False,
    )
    op.create_index("idx_cse_session_seq", "joysafeter_session_events", ["session_id", "seq"], unique=False)
    op.create_table(
        "joysafeter_session_memory_stores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("access", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("mount_name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["joysafeter_sessions.id"],
            name=op.f("fk_joysafeter_session_memory_stores_session_id_joysafeter_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["joysafeter_memory_stores.id"],
            name=op.f("fk_joysafeter_session_memory_stores_store_id_joysafeter_memory_stores"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_session_memory_stores")),
        sa.UniqueConstraint("session_id", "store_id", name=op.f("uq_joysafeter_session_memory_stores_session_id")),
    )
    op.create_table(
        "joysafeter_session_repos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("mount_path", sa.Text(), nullable=False),
        sa.Column("mount_name", sa.String(length=255), nullable=False),
        sa.Column("encrypted_token", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["joysafeter_sessions.id"],
            name=op.f("fk_joysafeter_session_repos_session_id_joysafeter_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_session_repos")),
    )
    op.create_index("idx_session_repos_session", "joysafeter_session_repos", ["session_id"], unique=False)
    op.create_table(
        "joysafeter_skill_versions",
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("release_notes", sa.Text(), nullable=True),
        sa.Column("skill_name", sa.String(length=64), nullable=False),
        sa.Column("skill_description", sa.String(length=1024), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("compatibility", sa.String(length=500), nullable=True),
        sa.Column("license", sa.String(length=100), nullable=True),
        sa.Column("published_by_id", sa.String(length=255), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("security_scan_id", sa.UUID(), nullable=True),
        sa.Column("target_hash", sa.String(length=64), nullable=True),
        sa.Column("lifecycle_status", sa.String(length=16), nullable=False),
        sa.Column("approved_by_id", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_skill_versions_approved_by_id_joysafeter_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_id"],
            ["joysafeter_users.id"],
            name=op.f("fk_joysafeter_skill_versions_published_by_id_joysafeter_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["security_scan_id"],
            ["joysafeter_skill_security_scans.id"],
            name=op.f("fk_joysafeter_skill_versions_security_scan_id_joysafeter_skill_security_scans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["joysafeter_skills.id"],
            name=op.f("fk_joysafeter_skill_versions_skill_id_joysafeter_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_skill_versions")),
        sa.UniqueConstraint("skill_id", "version", name="skill_versions_skill_version_unique"),
    )
    op.create_index(
        "skill_versions_lifecycle_status_idx", "joysafeter_skill_versions", ["lifecycle_status"], unique=False
    )
    op.create_index("skill_versions_published_at_idx", "joysafeter_skill_versions", ["published_at"], unique=False)
    op.create_index("skill_versions_security_scan_idx", "joysafeter_skill_versions", ["security_scan_id"], unique=False)
    op.create_index("skill_versions_skill_idx", "joysafeter_skill_versions", ["skill_id"], unique=False)
    op.create_table(
        "joysafeter_tasks",
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("chat_session_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("sandbox_id", sa.UUID(), nullable=True),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timeout_sec", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["joysafeter_agents.id"], name=op.f("fk_joysafeter_tasks_agent_id_joysafeter_agents")
        ),
        sa.ForeignKeyConstraint(
            ["chat_session_id"],
            ["joysafeter_sessions.id"],
            name=op.f("fk_joysafeter_tasks_chat_session_id_joysafeter_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["joysafeter_organization_projects.id"],
            name=op.f("fk_joysafeter_tasks_project_id_joysafeter_organization_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_tasks")),
    )
    op.create_index("idx_ct_agent", "joysafeter_tasks", ["agent_id"], unique=False)
    op.create_index("idx_ct_created", "joysafeter_tasks", ["created_at"], unique=False)
    op.create_index("idx_ct_project", "joysafeter_tasks", ["project_id"], unique=False)
    op.create_index(
        "idx_ct_project_status_created", "joysafeter_tasks", ["project_id", "status", "created_at"], unique=False
    )
    op.create_index("idx_ct_sandbox_status", "joysafeter_tasks", ["sandbox_id", "status"], unique=False)
    op.create_index(
        "idx_ct_sandbox_status_created", "joysafeter_tasks", ["sandbox_id", "status", "created_at"], unique=False
    )
    op.create_index("idx_ct_status", "joysafeter_tasks", ["status"], unique=False)
    op.create_index("idx_ct_status_created", "joysafeter_tasks", ["status", "created_at"], unique=False)
    op.create_index("idx_ct_status_updated", "joysafeter_tasks", ["status", "updated_at"], unique=False)
    op.create_index(op.f("ix_joysafeter_tasks_project_id"), "joysafeter_tasks", ["project_id"], unique=False)
    op.create_table(
        "joysafeter_session_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("mount_path", sa.Text(), nullable=False),
        sa.Column("access", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["joysafeter_files.id"],
            name=op.f("fk_joysafeter_session_files_file_id_joysafeter_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["joysafeter_sessions.id"],
            name=op.f("fk_joysafeter_session_files_session_id_joysafeter_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_session_files")),
    )
    op.create_index("idx_session_files_file", "joysafeter_session_files", ["file_id"], unique=False)
    op.create_index("idx_session_files_session", "joysafeter_session_files", ["session_id"], unique=False)
    op.create_table(
        "joysafeter_skill_version_files",
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("storage_type", sa.String(length=20), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["joysafeter_skill_versions.id"],
            name=op.f("fk_joysafeter_skill_version_files_version_id_joysafeter_skill_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_joysafeter_skill_version_files")),
    )
    op.create_index("skill_version_files_version_idx", "joysafeter_skill_version_files", ["version_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("skill_version_files_version_idx", table_name="joysafeter_skill_version_files")
    op.drop_table("joysafeter_skill_version_files")
    op.drop_index("idx_session_files_session", table_name="joysafeter_session_files")
    op.drop_index("idx_session_files_file", table_name="joysafeter_session_files")
    op.drop_table("joysafeter_session_files")
    op.drop_index(op.f("ix_joysafeter_tasks_project_id"), table_name="joysafeter_tasks")
    op.drop_index("idx_ct_status_updated", table_name="joysafeter_tasks")
    op.drop_index("idx_ct_status_created", table_name="joysafeter_tasks")
    op.drop_index("idx_ct_status", table_name="joysafeter_tasks")
    op.drop_index("idx_ct_sandbox_status_created", table_name="joysafeter_tasks")
    op.drop_index("idx_ct_sandbox_status", table_name="joysafeter_tasks")
    op.drop_index("idx_ct_project_status_created", table_name="joysafeter_tasks")
    op.drop_index("idx_ct_project", table_name="joysafeter_tasks")
    op.drop_index("idx_ct_created", table_name="joysafeter_tasks")
    op.drop_index("idx_ct_agent", table_name="joysafeter_tasks")
    op.drop_table("joysafeter_tasks")
    op.drop_index("skill_versions_skill_idx", table_name="joysafeter_skill_versions")
    op.drop_index("skill_versions_security_scan_idx", table_name="joysafeter_skill_versions")
    op.drop_index("skill_versions_published_at_idx", table_name="joysafeter_skill_versions")
    op.drop_index("skill_versions_lifecycle_status_idx", table_name="joysafeter_skill_versions")
    op.drop_table("joysafeter_skill_versions")
    op.drop_index("idx_session_repos_session", table_name="joysafeter_session_repos")
    op.drop_table("joysafeter_session_repos")
    op.drop_table("joysafeter_session_memory_stores")
    op.drop_index("idx_cse_session_seq", table_name="joysafeter_session_events")
    op.drop_index("idx_cse_session_processed_event", table_name="joysafeter_session_events")
    op.drop_index("idx_cse_session_event_seq", table_name="joysafeter_session_events")
    op.drop_index("idx_cse_event_created", table_name="joysafeter_session_events")
    op.drop_index("idx_cse_created_at", table_name="joysafeter_session_events")
    op.drop_table("joysafeter_session_events")
    op.drop_index(op.f("ix_joysafeter_files_project_id"), table_name="joysafeter_files")
    op.drop_index("idx_joysafeter_files_session", table_name="joysafeter_files")
    op.drop_index("idx_joysafeter_files_project_created", table_name="joysafeter_files")
    op.drop_table("joysafeter_files")
    op.drop_table("joysafeter_vault_credentials")
    op.drop_index("skill_usage_log_skill_created_idx", table_name="joysafeter_skill_usage_log")
    op.drop_index("skill_usage_log_session_created_idx", table_name="joysafeter_skill_usage_log")
    op.drop_index("skill_usage_log_project_created_idx", table_name="joysafeter_skill_usage_log")
    op.drop_table("joysafeter_skill_usage_log")
    op.drop_index("skill_security_scans_target_hash_idx", table_name="joysafeter_skill_security_scans")
    op.drop_index("skill_security_scans_status_created_idx", table_name="joysafeter_skill_security_scans")
    op.drop_index("skill_security_scans_skill_created_idx", table_name="joysafeter_skill_security_scans")
    op.drop_index("skill_security_scans_severity_created_idx", table_name="joysafeter_skill_security_scans")
    op.drop_index("skill_security_scans_recommendation_created_idx", table_name="joysafeter_skill_security_scans")
    op.drop_index("skill_security_scans_project_created_idx", table_name="joysafeter_skill_security_scans")
    op.drop_index("skill_security_scans_owner_created_idx", table_name="joysafeter_skill_security_scans")
    op.drop_table("joysafeter_skill_security_scans")
    op.drop_index("skill_files_skill_idx", table_name="joysafeter_skill_files")
    op.drop_index("skill_files_path_idx", table_name="joysafeter_skill_files")
    op.drop_table("joysafeter_skill_files")
    op.drop_index("skill_collaborators_user_skill_idx", table_name="joysafeter_skill_collaborators")
    op.drop_table("joysafeter_skill_collaborators")
    op.drop_index(op.f("ix_joysafeter_sessions_project_id"), table_name="joysafeter_sessions")
    op.drop_index("idx_csess_project", table_name="joysafeter_sessions")
    op.drop_index("idx_csess_created", table_name="joysafeter_sessions")
    op.drop_index("idx_csess_agent", table_name="joysafeter_sessions")
    op.drop_table("joysafeter_sessions")
    op.drop_table("joysafeter_memory_versions")
    op.drop_table("joysafeter_memories")
    op.drop_table("joysafeter_agent_versions")
    op.drop_index(op.f("ix_joysafeter_vaults_project_id"), table_name="joysafeter_vaults")
    op.drop_index("idx_cv_project", table_name="joysafeter_vaults")
    op.drop_table("joysafeter_vaults")
    op.drop_index("skills_visibility_idx", table_name="joysafeter_skills")
    op.drop_index("skills_tags_idx", table_name="joysafeter_skills", postgresql_using="gin")
    op.drop_index("skills_security_status_idx", table_name="joysafeter_skills")
    op.drop_index("skills_security_severity_idx", table_name="joysafeter_skills")
    op.drop_index("skills_security_recommendation_idx", table_name="joysafeter_skills")
    op.drop_index("skills_public_idx", table_name="joysafeter_skills")
    op.drop_index("skills_project_idx", table_name="joysafeter_skills")
    op.drop_index("skills_owner_idx", table_name="joysafeter_skills")
    op.drop_index("skills_lifecycle_status_idx", table_name="joysafeter_skills")
    op.drop_index("skills_created_by_idx", table_name="joysafeter_skills")
    op.drop_table("joysafeter_skills")
    op.drop_index(op.f("ix_joysafeter_secrets_project_id"), table_name="joysafeter_secrets")
    op.drop_table("joysafeter_secrets")
    op.drop_index(op.f("ix_joysafeter_sandboxes_project_id"), table_name="joysafeter_sandboxes")
    op.drop_index("idx_csb_status", table_name="joysafeter_sandboxes")
    op.drop_index("idx_csb_session", table_name="joysafeter_sandboxes", postgresql_where="chat_session_id IS NOT NULL")
    op.drop_index("idx_csb_project", table_name="joysafeter_sandboxes")
    op.drop_index("idx_csb_pool", table_name="joysafeter_sandboxes", postgresql_where="status = 'pooled'")
    op.drop_index(
        "idx_csb_active_session_unique",
        table_name="joysafeter_sandboxes",
        postgresql_where="chat_session_id IS NOT NULL AND destroyed_at IS NULL AND status IN ('creating', 'provisioning', 'idle', 'running', 'stopped', 'error')",
    )
    op.drop_table("joysafeter_sandboxes")
    op.drop_index("ix_joysafeter_project_members_user_id", table_name="joysafeter_project_members")
    op.drop_index("ix_joysafeter_project_members_project_id", table_name="joysafeter_project_members")
    op.drop_table("joysafeter_project_members")
    op.drop_index(op.f("ix_joysafeter_memory_stores_project_id"), table_name="joysafeter_memory_stores")
    op.drop_table("joysafeter_memory_stores")
    op.drop_index(op.f("ix_joysafeter_environments_project_id"), table_name="joysafeter_environments")
    op.drop_table("joysafeter_environments")
    op.drop_index("idx_cak_project", table_name="joysafeter_api_keys")
    op.drop_index("idx_cak_org", table_name="joysafeter_api_keys")
    op.drop_index("idx_cak_key_hash", table_name="joysafeter_api_keys")
    op.drop_table("joysafeter_api_keys")
    op.drop_index(op.f("ix_joysafeter_agents_project_id"), table_name="joysafeter_agents")
    op.drop_index("idx_ca_project", table_name="joysafeter_agents")
    op.drop_index("idx_ca_created_at", table_name="joysafeter_agents")
    op.drop_table("joysafeter_agents")
    op.drop_index("ix_joysafeter_organization_projects_org_id", table_name="joysafeter_organization_projects")
    op.drop_table("joysafeter_organization_projects")
    op.drop_index("ix_joysafeter_organization_members_user_id", table_name="joysafeter_organization_members")
    op.drop_index("ix_joysafeter_organization_members_organization_id", table_name="joysafeter_organization_members")
    op.drop_table("joysafeter_organization_members")
    op.drop_index("ix_joysafeter_oauth_account_user_id", table_name="joysafeter_oauth_account")
    op.drop_index("ix_joysafeter_oauth_account_provider_account", table_name="joysafeter_oauth_account")
    op.drop_table("joysafeter_oauth_account")
    op.drop_index("ix_joysafeter_auth_sessions_user_id", table_name="joysafeter_auth_sessions")
    op.drop_index("ix_joysafeter_auth_sessions_token", table_name="joysafeter_auth_sessions")
    op.drop_table("joysafeter_auth_sessions")
    op.drop_index(op.f("ix_joysafeter_users_email"), table_name="joysafeter_users")
    op.drop_table("joysafeter_users")
    op.drop_index("ix_joysafeter_security_audit_logs_user_id", table_name="joysafeter_security_audit_logs")
    op.drop_index("ix_joysafeter_security_audit_logs_user_event", table_name="joysafeter_security_audit_logs")
    op.drop_index("ix_joysafeter_security_audit_logs_event_type", table_name="joysafeter_security_audit_logs")
    op.drop_index("ix_joysafeter_security_audit_logs_event_status", table_name="joysafeter_security_audit_logs")
    op.drop_index("ix_joysafeter_security_audit_logs_created_at", table_name="joysafeter_security_audit_logs")
    op.drop_table("joysafeter_security_audit_logs")
    op.drop_table("joysafeter_organizations")
    # ### end Alembic commands ###
