"""add model provider template columns

Revision ID: 0faa0dc41210
Revises: afb42e79eefb
Create Date: 2026-03-07 11:10:00.000000+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0faa0dc41210"
down_revision: Union[str, None] = "afb42e79eefb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_provider", sa.Column("is_template", sa.Boolean(), nullable=False, server_default="false", comment="是否为模板（用于创建自定义供应商）"))
    op.add_column("model_provider", sa.Column("template_name", sa.String(length=100), nullable=True, comment="引用模板的名称"))
    op.add_column("model_provider", sa.Column("provider_type", sa.String(length=50), nullable=False, server_default="system", comment="供应商类型：system, custom"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_provider", "provider_type")
    op.drop_column("model_provider", "template_name")
    op.drop_column("model_provider", "is_template")
    # ### end Alembic commands ###
