"""Canonical error contract values — source of truth for error metadata.

Mirrors the pattern of agent.py and execution.py: StrEnum for type-safe
values, Literal types for function signatures, plain sets for runtime checks.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Literal


# ---------------------------------------------------------------------------
# Error source — classifies where the failure originated
# ---------------------------------------------------------------------------
class ErrorSource(StrEnum):
    API = "api"
    ENGINE = "engine"
    RUNTIME = "runtime"
    NODE = "node"
    TOOL = "tool"
    WEBSOCKET = "websocket"
    AUTH = "auth"
    VALIDATION = "validation"
    PERMISSION = "permission"
    INTERNAL = "internal"


ErrorSourceLiteral = Literal[
    "api",
    "engine",
    "runtime",
    "node",
    "tool",
    "websocket",
    "auth",
    "validation",
    "permission",
    "internal",
]

ERROR_SOURCES: set[str] = {s.value for s in ErrorSource}


# ---------------------------------------------------------------------------
# User action — what the user should do to resolve the failure
# ---------------------------------------------------------------------------
class UserAction(StrEnum):
    RETRY = "retry"
    CONFIGURE_MODEL = "configure_model"
    RELOGIN = "relogin"
    FIX_INPUT = "fix_input"
    CONTACT_SUPPORT = "contact_support"


UserActionLiteral = Literal[
    "retry",
    "configure_model",
    "relogin",
    "fix_input",
    "contact_support",
]

USER_ACTIONS: set[str] = {a.value for a in UserAction}


# ---------------------------------------------------------------------------
# Error codes — the canonical registry of all product error codes.
#
# Every error code used anywhere in backend must have an entry here.
# StrEnum values compare equal to their string values, so existing call
# sites using raw strings remain compatible during gradual migration.
# ---------------------------------------------------------------------------
class ErrorCode(StrEnum):
    # -- Generic --
    NOT_FOUND = "NOT_FOUND"
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    CLIENT_CLOSED = "CLIENT_CLOSED"
    REQUEST_VALIDATION_ERROR = "REQUEST_VALIDATION_ERROR"
    SUPERUSER_REQUIRED = "SUPERUSER_REQUIRED"

    # -- Auth --
    AUTH_REQUIRED = "AUTH_REQUIRED"
    BEARER_TOKEN_MISSING = "BEARER_TOKEN_MISSING"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_REFRESH_FAILED = "TOKEN_REFRESH_FAILED"
    TOKEN_REFRESH_UNAVAILABLE = "TOKEN_REFRESH_UNAVAILABLE"
    TOKEN_RESOURCE_ID_INVALID = "TOKEN_RESOURCE_ID_INVALID"
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"
    RESET_TOKEN_INVALID = "RESET_TOKEN_INVALID"
    RESET_TOKEN_EXPIRED = "RESET_TOKEN_EXPIRED"
    VERIFICATION_TOKEN_INVALID = "VERIFICATION_TOKEN_INVALID"
    VERIFICATION_TOKEN_EXPIRED = "VERIFICATION_TOKEN_EXPIRED"
    CREDENTIALS_INVALID = "CREDENTIALS_INVALID"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    MISSING_CREDENTIALS = "MISSING_CREDENTIALS"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"

    # -- User --
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_INACTIVE = "USER_INACTIVE"
    USER_INVALID = "USER_INVALID"

    # -- Agent --
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    AGENT_NOT_PUBLISHED = "AGENT_NOT_PUBLISHED"
    AGENT_ACTIVE_RELEASE_MISSING = "AGENT_ACTIVE_RELEASE_MISSING"
    AGENT_DRAFT_VERSION_MISSING = "AGENT_DRAFT_VERSION_MISSING"
    AGENT_DRAFT_VERSION_NOT_FOUND = "AGENT_DRAFT_VERSION_NOT_FOUND"
    AGENT_WORKSPACE_MISMATCH = "AGENT_WORKSPACE_MISMATCH"
    AGENT_DEFINITION_KIND_UNSUPPORTED = "AGENT_DEFINITION_KIND_UNSUPPORTED"
    AGENT_DELETE_TASK_REFERENCE_CONFLICT = "AGENT_DELETE_TASK_REFERENCE_CONFLICT"
    AGENT_VERSION_NOT_FOUND = "AGENT_VERSION_NOT_FOUND"
    AGENT_VERSION_AGENT_MISMATCH = "AGENT_VERSION_AGENT_MISMATCH"
    AGENT_VERSION_NOT_FROZEN = "AGENT_VERSION_NOT_FROZEN"
    AGENT_RELEASE_NOT_FOUND = "AGENT_RELEASE_NOT_FOUND"
    AGENT_RELEASE_NOT_ACTIVATABLE = "AGENT_RELEASE_NOT_ACTIVATABLE"
    AGENT_RELEASE_ACTIVE_CANNOT_RETIRE = "AGENT_RELEASE_ACTIVE_CANNOT_RETIRE"
    AGENT_RELEASE_AGENT_MISMATCH = "AGENT_RELEASE_AGENT_MISMATCH"
    AGENT_RUN_NOT_FOUND = "AGENT_RUN_NOT_FOUND"
    AGENT_RUN_FILTER_REQUIRED = "AGENT_RUN_FILTER_REQUIRED"
    AGENT_RUN_WORKSPACE_REQUIRED = "AGENT_RUN_WORKSPACE_REQUIRED"

    # -- Run --
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    RUN_BINDING_INVALID = "RUN_BINDING_INVALID"
    RUN_CANCEL_STATUS_INVALID = "RUN_CANCEL_STATUS_INVALID"
    RUN_RETRY_STATUS_INVALID = "RUN_RETRY_STATUS_INVALID"
    RUN_RETRY_DRAFT_FORBIDDEN = "RUN_RETRY_DRAFT_FORBIDDEN"
    RETRY_STATE_INVALID = "RETRY_STATE_INVALID"

    # -- Execution --
    EXECUTION_NOT_FOUND = "EXECUTION_NOT_FOUND"
    EXECUTION_SNAPSHOT_NOT_FOUND = "EXECUTION_SNAPSHOT_NOT_FOUND"
    EXECUTION_ENGINE_FAILED = "EXECUTION_ENGINE_FAILED"
    EXECUTION_ENGINE_NOT_REGISTERED = "EXECUTION_ENGINE_NOT_REGISTERED"
    EXECUTION_EVENT_CONTEXT_MISSING = "EXECUTION_EVENT_CONTEXT_MISSING"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_MESSAGE_UNSUPPORTED = "EXECUTION_MESSAGE_UNSUPPORTED"
    EXECUTION_MESSAGE_REJECTED = "EXECUTION_MESSAGE_REJECTED"
    EXECUTION_OPERATION_UNSUPPORTED = "EXECUTION_OPERATION_UNSUPPORTED"
    EXECUTION_RUNTIME_KIND_MISSING = "EXECUTION_RUNTIME_KIND_MISSING"
    STALE_REAPED = "STALE_REAPED"
    DRAFT_OVERRIDE_PARAMETERS_INVALID = "DRAFT_OVERRIDE_PARAMETERS_INVALID"

    # -- Graph engine --
    GRAPH_DEFINITION_KIND_UNSUPPORTED = "GRAPH_DEFINITION_KIND_UNSUPPORTED"
    GRAPH_DEFINITION_NODES_EMPTY = "GRAPH_DEFINITION_NODES_EMPTY"
    GRAPH_EXECUTION_FAILED = "GRAPH_EXECUTION_FAILED"
    GRAPH_EXECUTION_NOT_RUNNING = "GRAPH_EXECUTION_NOT_RUNNING"
    GRAPH_EXECUTION_MESSAGE_UNSUPPORTED = "GRAPH_EXECUTION_MESSAGE_UNSUPPORTED"

    # -- Code engine --
    CODE_DEFINITION_EMPTY = "CODE_DEFINITION_EMPTY"
    CODE_DEFINITION_KIND_UNSUPPORTED = "CODE_DEFINITION_KIND_UNSUPPORTED"
    CODE_EXECUTION_FAILED = "CODE_EXECUTION_FAILED"
    CODE_EXECUTION_INVALID = "CODE_EXECUTION_INVALID"
    CODE_EXECUTION_NOT_RUNNING = "CODE_EXECUTION_NOT_RUNNING"
    CODE_EXECUTION_MESSAGE_UNSUPPORTED = "CODE_EXECUTION_MESSAGE_UNSUPPORTED"
    CODEX_THREAD_START_INVALID = "CODEX_THREAD_START_INVALID"

    # -- CLI engine --
    CLI_EXECUTION_RUNNER_FAILED = "CLI_EXECUTION_RUNNER_FAILED"
    CLAUDE_CODE_RUNTIME_ERROR = "CLAUDE_CODE_RUNTIME_ERROR"
    CODEX_RUNTIME_ERROR = "CODEX_RUNTIME_ERROR"
    RUNTIME_PROVIDER_NOT_FOUND = "RUNTIME_PROVIDER_NOT_FOUND"

    # -- Copilot --
    AGENT_ERROR = "AGENT_ERROR"
    CREDENTIAL_ERROR = "CREDENTIAL_ERROR"
    CANCELLED = "CANCELLED"
    COPILOT_EXECUTION_FAILED = "COPILOT_EXECUTION_FAILED"
    COPILOT_EXECUTION_MESSAGE_UNSUPPORTED = "COPILOT_EXECUTION_MESSAGE_UNSUPPORTED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

    # -- Event bus --
    EVENT_ERROR_PAYLOAD_MISSING = "EVENT_ERROR_PAYLOAD_MISSING"
    EVENT_SUBSCRIBER_DB_SESSION_MISSING = "EVENT_SUBSCRIBER_DB_SESSION_MISSING"
    EVENT_TARGET_STATUS_MISSING = "EVENT_TARGET_STATUS_MISSING"
    EVENT_TERMINAL_STATUS_MISSING = "EVENT_TERMINAL_STATUS_MISSING"
    EVENT_TERMINAL_STATUS_INVALID = "EVENT_TERMINAL_STATUS_INVALID"

    # -- State machine --
    STATE_TRANSITION_INVALID = "STATE_TRANSITION_INVALID"

    # -- Model --
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    MODEL_NO_CREDENTIALS = "MODEL_NO_CREDENTIALS"
    MODEL_NAME_REQUIRED = "MODEL_NAME_REQUIRED"
    MODEL_TYPE_UNSUPPORTED = "MODEL_TYPE_UNSUPPORTED"
    MODEL_STREAM_ERROR = "MODEL_STREAM_ERROR"
    MODEL_INSTANCE_NOT_FOUND = "MODEL_INSTANCE_NOT_FOUND"
    MODEL_INSTANCE_CREATE_FAILED = "MODEL_INSTANCE_CREATE_FAILED"
    MODEL_PROVIDER_NOT_FOUND = "MODEL_PROVIDER_NOT_FOUND"
    MODEL_PROVIDER_OR_NAME_REQUIRED = "MODEL_PROVIDER_OR_NAME_REQUIRED"
    MODEL_PROVIDER_DELETE_FORBIDDEN = "MODEL_PROVIDER_DELETE_FORBIDDEN"
    MODEL_PROVIDER_BUILTIN_DELETE_FORBIDDEN = "MODEL_PROVIDER_BUILTIN_DELETE_FORBIDDEN"
    MODEL_CREDENTIAL_NOT_FOUND = "MODEL_CREDENTIAL_NOT_FOUND"
    MODEL_CREDENTIAL_CUSTOM_DELETE_FORBIDDEN = "MODEL_CREDENTIAL_CUSTOM_DELETE_FORBIDDEN"
    BUILD_COPILOT_MODEL_REQUIRED = "BUILD_COPILOT_MODEL_REQUIRED"

    # -- Sandbox --
    SANDBOX_NOT_FOUND = "SANDBOX_NOT_FOUND"
    SANDBOX_NOT_RUNNING = "SANDBOX_NOT_RUNNING"
    SANDBOX_ACCESS_DENIED = "SANDBOX_ACCESS_DENIED"
    SANDBOX_SETUP_FAILED = "SANDBOX_SETUP_FAILED"
    SANDBOX_STOP_TARGET_NOT_FOUND = "SANDBOX_STOP_TARGET_NOT_FOUND"
    SANDBOX_IMAGE_EMPTY = "SANDBOX_IMAGE_EMPTY"
    SANDBOX_IMAGE_TOO_LONG = "SANDBOX_IMAGE_TOO_LONG"
    SANDBOX_PROVIDER_UNKNOWN = "SANDBOX_PROVIDER_UNKNOWN"
    DOCKER_DAEMON_UNAVAILABLE = "DOCKER_DAEMON_UNAVAILABLE"
    DOCKER_COMMAND_FAILED = "DOCKER_COMMAND_FAILED"
    DOCKER_EXECUTOR_DEPENDENCY_MISSING = "DOCKER_EXECUTOR_DEPENDENCY_MISSING"
    DOCKER_EXECUTOR_INIT_FAILED = "DOCKER_EXECUTOR_INIT_FAILED"
    DOCKER_SANDBOX_CREATE_FAILED = "DOCKER_SANDBOX_CREATE_FAILED"
    DOCKER_SANDBOX_START_FAILED = "DOCKER_SANDBOX_START_FAILED"
    MODAL_SANDBOX_STARTUP_FAILED = "MODAL_SANDBOX_STARTUP_FAILED"
    MODAL_SANDBOX_STARTUP_TIMEOUT = "MODAL_SANDBOX_STARTUP_TIMEOUT"
    RUNLOOP_API_KEY_MISSING = "RUNLOOP_API_KEY_MISSING"
    RUNLOOP_DEVBOX_STARTUP_TIMEOUT = "RUNLOOP_DEVBOX_STARTUP_TIMEOUT"
    CHECKPOINTER_DISABLED = "CHECKPOINTER_DISABLED"
    CHECKPOINTER_POOL_UNINITIALIZED = "CHECKPOINTER_POOL_UNINITIALIZED"
    CHECKPOINTER_MANAGER_UNINITIALIZED = "CHECKPOINTER_MANAGER_UNINITIALIZED"
    DEEPAGENTS_UNAVAILABLE = "DEEPAGENTS_UNAVAILABLE"

    # -- Skill --
    SKILL_NOT_FOUND = "SKILL_NOT_FOUND"
    SKILL_ACCESS_DENIED = "SKILL_ACCESS_DENIED"
    SKILL_DELETE_FORBIDDEN = "SKILL_DELETE_FORBIDDEN"
    SKILL_NAME_ALREADY_EXISTS = "SKILL_NAME_ALREADY_EXISTS"
    SKILL_NAME_INVALID = "SKILL_NAME_INVALID"
    SKILL_OWNER_COLLABORATOR_FORBIDDEN = "SKILL_OWNER_COLLABORATOR_FORBIDDEN"
    SKILL_OWNER_TRANSFER_FORBIDDEN = "SKILL_OWNER_TRANSFER_FORBIDDEN"
    SKILL_TOKEN_SCOPE_FORBIDDEN = "SKILL_TOKEN_SCOPE_FORBIDDEN"
    SKILL_COLLABORATOR_NOT_FOUND = "SKILL_COLLABORATOR_NOT_FOUND"
    SKILL_COLLABORATOR_ALREADY_EXISTS = "SKILL_COLLABORATOR_ALREADY_EXISTS"
    SKILL_VERSION_NOT_FOUND = "SKILL_VERSION_NOT_FOUND"
    SKILL_VERSION_FORMAT_INVALID = "SKILL_VERSION_FORMAT_INVALID"
    SKILL_VERSION_NOT_GREATER_THAN_LATEST = "SKILL_VERSION_NOT_GREATER_THAN_LATEST"
    SKILL_VERSION_PRERELEASE_UNSUPPORTED = "SKILL_VERSION_PRERELEASE_UNSUPPORTED"
    SKILL_IMPORT_FILES_INVALID = "SKILL_IMPORT_FILES_INVALID"
    SKILL_FILE_NOT_FOUND = "SKILL_FILE_NOT_FOUND"
    SKILL_FILE_CONTENT_INVALID = "SKILL_FILE_CONTENT_INVALID"
    SKILL_SYSTEM_FILE_IMPORT_FORBIDDEN = "SKILL_SYSTEM_FILE_IMPORT_FORBIDDEN"
    SKILL_LOAD_FAILED = "SKILL_LOAD_FAILED"
    SKILL_FILE_WRITE_FAILED = "SKILL_FILE_WRITE_FAILED"

    # -- Tool / MCP --
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"
    CUSTOM_TOOL_NOT_FOUND = "CUSTOM_TOOL_NOT_FOUND"
    CUSTOM_TOOL_NAME_ALREADY_EXISTS = "CUSTOM_TOOL_NAME_ALREADY_EXISTS"
    CUSTOM_TOOL_QUOTA_EXCEEDED = "CUSTOM_TOOL_QUOTA_EXCEEDED"
    CUSTOM_TOOL_VIEW_FORBIDDEN = "CUSTOM_TOOL_VIEW_FORBIDDEN"
    CUSTOM_TOOL_UPDATE_FORBIDDEN = "CUSTOM_TOOL_UPDATE_FORBIDDEN"
    CUSTOM_TOOL_DELETE_FORBIDDEN = "CUSTOM_TOOL_DELETE_FORBIDDEN"
    MCP_SERVER_NOT_FOUND = "MCP_SERVER_NOT_FOUND"
    MCP_SERVER_NAME_ALREADY_EXISTS = "MCP_SERVER_NAME_ALREADY_EXISTS"
    MCP_SERVER_URL_REQUIRED = "MCP_SERVER_URL_REQUIRED"
    MCP_SERVER_IDENTIFIER_INVALID = "MCP_SERVER_IDENTIFIER_INVALID"
    MCP_SERVER_ACCESS_DENIED = "MCP_SERVER_ACCESS_DENIED"
    MCP_SERVER_CONNECTION_FAILED = "MCP_SERVER_CONNECTION_FAILED"
    MCP_SERVER_DISABLED = "MCP_SERVER_DISABLED"
    MCP_SERVER_REFRESH_DISABLED = "MCP_SERVER_REFRESH_DISABLED"
    MCP_SERVER_RESOLVE_FAILED = "MCP_SERVER_RESOLVE_FAILED"
    MCP_SERVER_TOGGLE_TARGET_MISSING = "MCP_SERVER_TOGGLE_TARGET_MISSING"
    MCP_SERVER_UPDATE_TARGET_MISSING = "MCP_SERVER_UPDATE_TARGET_MISSING"
    MCP_TOOL_NOT_FOUND = "MCP_TOOL_NOT_FOUND"
    MCP_TOOL_EXECUTION_FAILED = "MCP_TOOL_EXECUTION_FAILED"
    MCP_TOOLKIT_SESSION_MISSING = "MCP_TOOLKIT_SESSION_MISSING"
    MCP_STARTUP_SYNC_FAILED = "MCP_STARTUP_SYNC_FAILED"

    # -- Task --
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_AGENT_MISSING = "TASK_AGENT_MISSING"
    TASK_PRIORITY_INVALID = "TASK_PRIORITY_INVALID"
    TASK_STATUS_INVALID = "TASK_STATUS_INVALID"
    TASK_STATUS_NOT_DISPATCHABLE = "TASK_STATUS_NOT_DISPATCHABLE"
    TASK_STATUS_TRANSITION_INVALID = "TASK_STATUS_TRANSITION_INVALID"
    TASK_RUN_ALREADY_ACTIVE = "TASK_RUN_ALREADY_ACTIVE"
    TASK_ACTIVITY_NOT_FOUND = "TASK_ACTIVITY_NOT_FOUND"

    # -- Thread --
    THREAD_NOT_FOUND = "THREAD_NOT_FOUND"
    THREAD_ACTIVE_RUN_EXISTS = "THREAD_ACTIVE_RUN_EXISTS"

    # -- File --
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_EMPTY = "FILE_EMPTY"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_TYPE_UNSUPPORTED = "FILE_TYPE_UNSUPPORTED"
    FILE_CONTENT_TYPE_MISMATCH = "FILE_CONTENT_TYPE_MISMATCH"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_WRITE_FAILED = "FILE_WRITE_FAILED"
    FILE_READ_FAILED = "FILE_READ_FAILED"
    FILE_DELETE_FAILED = "FILE_DELETE_FAILED"
    FILE_LIST_FAILED = "FILE_LIST_FAILED"
    FILE_CLEAR_FAILED = "FILE_CLEAR_FAILED"

    # -- Artifact --
    ARTIFACT_FILE_NOT_FOUND = "ARTIFACT_FILE_NOT_FOUND"
    ARTIFACT_FILE_READ_FAILED = "ARTIFACT_FILE_READ_FAILED"
    ARTIFACT_RUN_DELETE_FAILED = "ARTIFACT_RUN_DELETE_FAILED"

    # -- Memory --
    MEMORY_NOT_FOUND = "MEMORY_NOT_FOUND"
    MEMORY_CREATE_FAILED = "MEMORY_CREATE_FAILED"
    MEMORY_UPDATE_FAILED = "MEMORY_UPDATE_FAILED"
    MEMORY_IDS_EMPTY = "MEMORY_IDS_EMPTY"
    MEMORY_TABLE_TYPE_UNSUPPORTED = "MEMORY_TABLE_TYPE_UNSUPPORTED"
    MEMORY_OPTIMIZATION_FAILED = "MEMORY_OPTIMIZATION_FAILED"
    MEMORY_OPTIMIZATION_MODEL_REQUIRED = "MEMORY_OPTIMIZATION_MODEL_REQUIRED"
    MEMORY_OPTIMIZATION_MODEL_INVALID = "MEMORY_OPTIMIZATION_MODEL_INVALID"

    # -- Trace --
    TRACE_NOT_FOUND = "TRACE_NOT_FOUND"

    # -- Workspace --
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    WORKSPACE_ACCESS_DENIED = "WORKSPACE_ACCESS_DENIED"
    WORKSPACE_PERMISSION_DENIED = "WORKSPACE_PERMISSION_DENIED"
    WORKSPACE_TYPE_INVALID = "WORKSPACE_TYPE_INVALID"
    WORKSPACE_MEMBER_NOT_FOUND = "WORKSPACE_MEMBER_NOT_FOUND"
    WORKSPACE_MEMBER_ALREADY_EXISTS = "WORKSPACE_MEMBER_ALREADY_EXISTS"
    WORKSPACE_MEMBER_ROLE_INVALID = "WORKSPACE_MEMBER_ROLE_INVALID"
    WORKSPACE_MEMBER_ROLE_TOO_HIGH = "WORKSPACE_MEMBER_ROLE_TOO_HIGH"
    WORKSPACE_OWNER_REMOVE_FORBIDDEN = "WORKSPACE_OWNER_REMOVE_FORBIDDEN"
    WORKSPACE_OWNER_ROLE_CHANGE_FORBIDDEN = "WORKSPACE_OWNER_ROLE_CHANGE_FORBIDDEN"
    WORKSPACE_OWNER_ROLE_ASSIGNMENT_FORBIDDEN = "WORKSPACE_OWNER_ROLE_ASSIGNMENT_FORBIDDEN"
    WORKSPACE_LAST_ADMIN_REMOVE_FORBIDDEN = "WORKSPACE_LAST_ADMIN_REMOVE_FORBIDDEN"
    PERSONAL_WORKSPACE_DELETE_FORBIDDEN = "PERSONAL_WORKSPACE_DELETE_FORBIDDEN"
    PERSONAL_WORKSPACE_DUPLICATE_FORBIDDEN = "PERSONAL_WORKSPACE_DUPLICATE_FORBIDDEN"

    # -- Organization --
    ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND"
    ORGANIZATION_ACCESS_DENIED = "ORGANIZATION_ACCESS_DENIED"
    ORGANIZATION_PERMISSION_DENIED = "ORGANIZATION_PERMISSION_DENIED"
    ORGANIZATION_SLUG_ALREADY_EXISTS = "ORGANIZATION_SLUG_ALREADY_EXISTS"
    ORGANIZATION_PLAN_UNSUPPORTED = "ORGANIZATION_PLAN_UNSUPPORTED"
    ORGANIZATION_SEATS_INVALID = "ORGANIZATION_SEATS_INVALID"
    ORGANIZATION_SEATS_BELOW_MEMBER_COUNT = "ORGANIZATION_SEATS_BELOW_MEMBER_COUNT"
    ORGANIZATION_SEATS_UNAVAILABLE = "ORGANIZATION_SEATS_UNAVAILABLE"
    ORGANIZATION_MEMBER_NOT_FOUND = "ORGANIZATION_MEMBER_NOT_FOUND"
    ORGANIZATION_MEMBER_ALREADY_EXISTS = "ORGANIZATION_MEMBER_ALREADY_EXISTS"
    ORGANIZATION_MEMBER_ROLE_INVALID = "ORGANIZATION_MEMBER_ROLE_INVALID"
    ORGANIZATION_MEMBER_VIEW_FORBIDDEN = "ORGANIZATION_MEMBER_VIEW_FORBIDDEN"
    ORGANIZATION_MEMBER_ROLE_UPDATE_FORBIDDEN = "ORGANIZATION_MEMBER_ROLE_UPDATE_FORBIDDEN"
    ORGANIZATION_MEMBER_REMOVE_FORBIDDEN = "ORGANIZATION_MEMBER_REMOVE_FORBIDDEN"
    ORGANIZATION_OWNER_INVITE_FORBIDDEN = "ORGANIZATION_OWNER_INVITE_FORBIDDEN"
    ORGANIZATION_OWNER_REMOVE_FORBIDDEN = "ORGANIZATION_OWNER_REMOVE_FORBIDDEN"
    ORGANIZATION_OWNER_ROLE_MODIFY_FORBIDDEN = "ORGANIZATION_OWNER_ROLE_MODIFY_FORBIDDEN"
    ORGANIZATION_OWNER_ROLE_REASSIGN_FORBIDDEN = "ORGANIZATION_OWNER_ROLE_REASSIGN_FORBIDDEN"
    ORGANIZATION_ADMIN_PROMOTE_FORBIDDEN = "ORGANIZATION_ADMIN_PROMOTE_FORBIDDEN"
    ORGANIZATION_ADMIN_ROLE_TARGET_FORBIDDEN = "ORGANIZATION_ADMIN_ROLE_TARGET_FORBIDDEN"
    ORGANIZATION_ADMIN_REMOVE_TARGET_FORBIDDEN = "ORGANIZATION_ADMIN_REMOVE_TARGET_FORBIDDEN"

    # -- OAuth --
    OAUTH_PROVIDER_NOT_FOUND = "OAUTH_PROVIDER_NOT_FOUND"
    OAUTH_EMAIL_REQUIRED = "OAUTH_EMAIL_REQUIRED"
    OAUTH_REGISTRATION_DISABLED = "OAUTH_REGISTRATION_DISABLED"
    OAUTH_TOKEN_EXCHANGE_FAILED = "OAUTH_TOKEN_EXCHANGE_FAILED"
    OAUTH_USERINFO_FETCH_FAILED = "OAUTH_USERINFO_FETCH_FAILED"
    OAUTH_LAST_ACCOUNT_UNLINK_FORBIDDEN = "OAUTH_LAST_ACCOUNT_UNLINK_FORBIDDEN"

    # -- API token --
    API_TOKEN_INVALID = "API_TOKEN_INVALID"
    API_TOKEN_REVOKED = "API_TOKEN_REVOKED"
    API_TOKEN_EXPIRED = "API_TOKEN_EXPIRED"
    API_TOKEN_OWNER_INACTIVE = "API_TOKEN_OWNER_INACTIVE"

    # -- Platform token --
    PLATFORM_TOKEN_NOT_FOUND = "PLATFORM_TOKEN_NOT_FOUND"
    PLATFORM_TOKEN_LIMIT_EXCEEDED = "PLATFORM_TOKEN_LIMIT_EXCEEDED"
    PLATFORM_TOKEN_SCOPES_INVALID = "PLATFORM_TOKEN_SCOPES_INVALID"
    PLATFORM_TOKEN_REVOKE_FORBIDDEN = "PLATFORM_TOKEN_REVOKE_FORBIDDEN"
    PLATFORM_TOKEN_RESOURCE_TYPE_INVALID = "PLATFORM_TOKEN_RESOURCE_TYPE_INVALID"
    PLATFORM_TOKEN_RESOURCE_BINDING_INVALID = "PLATFORM_TOKEN_RESOURCE_BINDING_INVALID"
    PLATFORM_TOKEN_WORKSPACE_ACCESS_DENIED = "PLATFORM_TOKEN_WORKSPACE_ACCESS_DENIED"
    PLATFORM_TOKEN_TOOL_ACCESS_DENIED = "PLATFORM_TOKEN_TOOL_ACCESS_DENIED"
    PLATFORM_TOKEN_SKILL_ACCESS_DENIED = "PLATFORM_TOKEN_SKILL_ACCESS_DENIED"

    # -- WebSocket --
    WEBSOCKET_INVALID_JSON = "WEBSOCKET_INVALID_JSON"
    WEBSOCKET_UNKNOWN_FRAME_TYPE = "WEBSOCKET_UNKNOWN_FRAME_TYPE"
    WEBSOCKET_EXECUTION_ID_REQUIRED = "WEBSOCKET_EXECUTION_ID_REQUIRED"
    WEBSOCKET_INVALID_EXECUTION_ID = "WEBSOCKET_INVALID_EXECUTION_ID"
    WEBSOCKET_INVALID_AFTER_SEQ = "WEBSOCKET_INVALID_AFTER_SEQ"

    # -- OpenClaw --
    OPENCLAW_INSTANCE_NOT_FOUND = "OPENCLAW_INSTANCE_NOT_FOUND"
    OPENCLAW_INSTANCE_NOT_RUNNING = "OPENCLAW_INSTANCE_NOT_RUNNING"
    OPENCLAW_INSTANCE_START_FAILED = "OPENCLAW_INSTANCE_START_FAILED"
    OPENCLAW_INSTANCE_RESTART_FAILED = "OPENCLAW_INSTANCE_RESTART_FAILED"
    OPENCLAW_CONTAINER_NOT_FOUND = "OPENCLAW_CONTAINER_NOT_FOUND"
    OPENCLAW_CONTAINER_CREATE_FAILED = "OPENCLAW_CONTAINER_CREATE_FAILED"
    OPENCLAW_CONTAINER_STARTUP_FAILED = "OPENCLAW_CONTAINER_STARTUP_FAILED"
    OPENCLAW_GATEWAY_ENV_MISSING = "OPENCLAW_GATEWAY_ENV_MISSING"
    OPENCLAW_GATEWAY_TIMEOUT = "OPENCLAW_GATEWAY_TIMEOUT"
    OPENCLAW_PORT_POOL_EXHAUSTED = "OPENCLAW_PORT_POOL_EXHAUSTED"
    OPENCLAW_SKILL_SYNC_FAILED = "OPENCLAW_SKILL_SYNC_FAILED"
    OPENCLAW_STREAM_ERROR = "OPENCLAW_STREAM_ERROR"
    OPENCLAW_DEVICE_LIST_FAILED = "OPENCLAW_DEVICE_LIST_FAILED"
    OPENCLAW_DEVICE_COMMAND_FAILED = "OPENCLAW_DEVICE_COMMAND_FAILED"
    OPENCLAW_DEVICE_APPROVE_FAILED = "OPENCLAW_DEVICE_APPROVE_FAILED"
    OPENCLAW_DEVICE_APPROVE_ALL_FAILED = "OPENCLAW_DEVICE_APPROVE_ALL_FAILED"


ERROR_CODES: set[str] = {c.value for c in ErrorCode}
