apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: joysafeter-orchestrator
      namespace: joysafeter-control
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: joysafeter-orchestrator
        namespace: joysafeter-control
      spec:
        template:
          spec:
            volumes:
              - name: authz-server-tls
                secret:
                  secretName: joysafeter-egress-authz-server-tls
                  optional: true
              - name: xds-server-tls
                secret:
                  secretName: joysafeter-rust-xds-server-tls
                  optional: true
  - target:
      kind: DaemonSet
      name: joysafeter-egress-envoy
      namespace: joysafeter-egress
    patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: joysafeter-egress-envoy
        namespace: joysafeter-egress
      spec:
        template:
          spec:
            initContainers:
              - name: render-bootstrap
                args:
                  - >-
                    sed
                    -e "s|__POD_NAME__|${POD_NAME}|g"
                    -e "s|__NODE_NAME__|${NODE_NAME}|g"
                    /etc/joysafeter-egress-envoy-template/bootstrap-plaintext.yaml
                    > /etc/joysafeter-egress-envoy/bootstrap.yaml
            volumes:
              - name: xds-client-tls
                secret:
                  secretName: joysafeter-egress-envoy-xds-client-tls
                  optional: true
              - name: authz-client-tls
                secret:
                  secretName: joysafeter-egress-authz-client-tls
                  optional: true
              - name: downstream-server-tls
                secret:
                  secretName: joysafeter-egress-downstream-server-tls
                  optional: true
  - target:
      kind: ConfigMap
      name: joysafeter-config
      namespace: joysafeter-control
    patch: |-
      - op: replace
        path: /data/JOYSAFETER_EGRESS_AUTHZ_MTLS
        value: "false"
      - op: replace
        path: /data/JOYSAFETER_EGRESS_XDS_MTLS
        value: "false"
      - op: replace
        path: /data/JOYSAFETER_EGRESS_ENVOY_CREDENTIAL_URL
        value: http://joysafeter-egress-envoy.joysafeter-egress.svc.cluster.local:8443
      - op: replace
        path: /data/JOYSAFETER_EGRESS_ENVOY_FORWARD_PROXY_URL
        value: http://joysafeter-egress-envoy.joysafeter-egress.svc.cluster.local:8080
